eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8761/eureka/,http://eureka-server3:8763/eureka/
---
server:
  port: 18081
spring:
  profiles: user
  application:
    name: springcloud-config-user

---
server:
  port: 28081
spring:
  profiles: item
  application:
    name: springcloud-config-item